version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: muscle_fitness
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
